
services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - /var/www/node_modules
    depends_on:
      - db
    networks:
      - laravel_net
    command: ["php-fpm"]

  webserver:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - laravel_net

  vite:
    image: node:18
    container_name: vite_server
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - /var/www/node_modules
    command: [ "sh", "-c", "npm install && npm run dev -- --host" ]
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    networks:
      - laravel_net
    depends_on:
      - app

networks:
  laravel_net:

volumes:
  dbdata:
